### ISSUE TITLE
Some options in Windows 11 Fixer, can be applied without restarting but it asks to restart.

### ISSUE THREAD

**Issue by thefatos** [99natmar99/Windows-11-Fixer#2]
In Windows 11 fixer, theres a bug where, if you select a option in it (example: installing a app) it will still show to restart for some reason.

**Comment by 99natmar99** [comment]
For simplicity I initially decided to always request the user to perform a restart. It's usually good practice to perform a restart if performing numerous changes to your computer simultaneously. I will however be addressing this in a future update where I'll remove the restart popup for basic fixes that do not benefit from a computer restart.

**Comment by 99natmar99** [comment]
v1.1.1 now only displays the restart popup if any fixes applied require a computer restart (or explorer restart) to take effect.
