### ISSUE TITLE
removing edge not working

### ISSUE THREAD

**Issue by lollipop6969** [99natmar99/Windows-11-Fixer#4]
windows 11 21h2 (build 22000.527)

**Comment by 99natmar99** [comment]
Have you ever opened Edge before on your computer? If not, the computer hasn't created a value in the registry which contains the version number for the current installation of edge. Without this number, Windows 11 Fixer will fail to uninstall edge. I suggest opening Edge, making a random search, then closing it, and then trying to uninstall Edge again. Let me know if that works for you or not.
